export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const GET_ALL_BREEDS_FAILURE = "GET_ALL_BREEDS_FAILURE";
export const GET_ALL_TEMPERAMENTS_FAILURE = "GET_ALL_TEMPERAMENTS_FAILURE";
export const ADD_BREED_TO_FAVORITES= "ADD_BREED_TO_FAVORITES";
export const REMOVE_BREED_TO_FAVORITES = "REMOVE_BREED_TO_FAVORITES";
export const SET_FILTER = "SET_FILTER";
export const SET_ORDER = "SET_ORDER";

