export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const GET_ALL_BREEDS_FAILURE = "GET_ALL_BREEDS_FAILURE";
export const GET_ALL_TEMPERAMENTS_FAILURE = "GET_ALL_TEMPERAMENTS_FAILURE";
export const ADD_BREED_TO_FAVORITES= "ADD_BREED_TO_FAVORITES";
export const REMOVE_BREED_TO_FAVORITES = "REMOVE_BREED_TO_FAVORITES";
export const SET_FILTER = "SET_FILTER";
export const SET_ORDER = "SET_ORDER";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const SEARCH_BY_NAME_FAILURE = "SEARCH_BY_NAME_FAILURE";
export const GET_BREED_BY_ID = "GET_BREED_BY_ID";
export const GET_BREED_BY_ID_FAILURE = "GET_BREED_BY_ID_FAILURE";
export const CREATE_BREED = "CREATE_BREED";
export const CREATE_BREED_FAILURE = "CREATE_BREED_FAILURE";


